spring.application.name=otpGeneratorUtil-spring-boot-sample
server.port=9090
otp.suite=OCRA-1:HOTP-SHA256-6:TX-T30S
otp.otp-length=6
otp.time-step-seconds=3000
otp.crypto-algorithm=HmacSHA256
otp.allowed-clock-skew=1
otp.secret-encoding=UTF8
logging.level.com.tosan.client.redis=DEBUG
tedisson.local.cache-provider=ehcache
tedisson.redis.connection-type=single_node
tedisson.redis.enabled=false
tedisson.redis.username=default
tedisson.redis.password=
tedisson.redis.single-server.address=localhost:10501
tedisson.redis.single-server.database=10
tedisson.redis.stream.enabled=false
tedisson.redis.stream.max-message-size=10
tedisson.redis.stream.trim-rate-second=10
tedisson.redis.stream.thread-pool.core-pool-size=10
tedisson.redis.stream.thread-pool.queue-capacity=10
tedisson.redis.stream.thread-pool.max-pool-size=20

